---
- hosts: all
- become: true

  tasks:
    -name: Update apt cache
     apt: update_cache=yes

    -name: Install packages
     apt:
       name: "{{ packages }}"
       state: present
    vars:
    packages:
      -git
      -Ansible